version: 2

# Declare some defaults in order to reuse it.
# Use &name_here in order to declare it and *name_here in order to use it
job-defaults: &job-defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checks_and_build
      - deploy:
          requires:
            - checks_and_build
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master

jobs:
  checks_and_build:
    <<: *job-defaults

    steps:
      - checkout
        # Restore cache in order not not install node_modules every time
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn --non-interactive

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn lint
      - run: yarn test --collectCoverage
      - run: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *job-defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      - run: yarn semantic-release